// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSFEJZREfg7RXY90vMsLdQjbS8ncnVKgI',
    appId: '1:18935722220:web:ca5905b719fbbacd9a75c9',
    messagingSenderId: '18935722220',
    projectId: 'butlometr',
    authDomain: 'butlometr.firebaseapp.com',
    databaseURL: 'https://butlometr-default-rtdb.firebaseio.com',
    storageBucket: 'butlometr.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ3AnrAK74Mq_4hSwHWfXbdR5Et9Vkr9A',
    appId: '1:18935722220:android:dbb7510133dda99c9a75c9',
    messagingSenderId: '18935722220',
    projectId: 'butlometr',
    databaseURL: 'https://butlometr-default-rtdb.firebaseio.com',
    storageBucket: 'butlometr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtGLUmTU2Ev9S5C3LoWIS7o2i-rxSinoo',
    appId: '1:18935722220:ios:ac032c84a1f39ced9a75c9',
    messagingSenderId: '18935722220',
    projectId: 'butlometr',
    databaseURL: 'https://butlometr-default-rtdb.firebaseio.com',
    storageBucket: 'butlometr.appspot.com',
    iosBundleId: 'com.example.butlometr2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtGLUmTU2Ev9S5C3LoWIS7o2i-rxSinoo',
    appId: '1:18935722220:ios:251954a8195b99829a75c9',
    messagingSenderId: '18935722220',
    projectId: 'butlometr',
    databaseURL: 'https://butlometr-default-rtdb.firebaseio.com',
    storageBucket: 'butlometr.appspot.com',
    iosBundleId: 'com.example.butlometr2.RunnerTests',
  );
}
