// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaUXSQjTwVkd9RmqLFFyD9f2dX68Zh50Q',
    appId: '1:87633605635:web:a0c2651c60ecd18d224a36',
    messagingSenderId: '87633605635',
    projectId: 'pbl3-9609b',
    authDomain: 'pbl3-9609b.firebaseapp.com',
    databaseURL: 'https://pbl3-9609b-default-rtdb.firebaseio.com',
    storageBucket: 'pbl3-9609b.appspot.com',
    measurementId: 'G-2WS26B3L1T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeDL_Z7tBRaU2I6I4NEkuHdyUnONkH2Ho',
    appId: '1:87633605635:android:07f22b4c51393b78224a36',
    messagingSenderId: '87633605635',
    projectId: 'pbl3-9609b',
    databaseURL: 'https://pbl3-9609b-default-rtdb.firebaseio.com',
    storageBucket: 'pbl3-9609b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfrwBBljtYgdeIcHQ7DtHCgtFHkyEOpb4',
    appId: '1:87633605635:ios:8858a9d264f11d80224a36',
    messagingSenderId: '87633605635',
    projectId: 'pbl3-9609b',
    databaseURL: 'https://pbl3-9609b-default-rtdb.firebaseio.com',
    storageBucket: 'pbl3-9609b.appspot.com',
    iosBundleId: 'com.example.butlometr2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfrwBBljtYgdeIcHQ7DtHCgtFHkyEOpb4',
    appId: '1:87633605635:ios:0e5f543e7a705b55224a36',
    messagingSenderId: '87633605635',
    projectId: 'pbl3-9609b',
    databaseURL: 'https://pbl3-9609b-default-rtdb.firebaseio.com',
    storageBucket: 'pbl3-9609b.appspot.com',
    iosBundleId: 'com.example.butlometr2.RunnerTests',
  );
}
